### ISSUE TITLE
Action to open uploaded image in default browser

### ISSUE THREAD

**Issue by Atheuz** [factormystic/ProSnap#4]
As in imgyazur

**Comment by factormystic** [comment]
This can be done with a Run action item, as long as the upload image url is available as a parameter. A better interface to choose which program to execute is probably in order, as a chooser for the raw file path.

**Comment by factormystic** [comment]
Now that I added upload image urls in f5c95f99591fa8ac52cf031a9bb3f2ad1156ee32, I changed the auto upload handler (which remains `ctrl` + `shift` + `print screen`) to open the image in the default browser automatically as a Run action (1cfac6f73f392b5b0332aed4c489bd809fd30539).

![20130308_112748PM Action Properties](https://f.cloud.github.com/assets/43428/239269/dffc4c94-8871-11e2-9fe2-9e65cfa4814a.png)
